export const GET_DRIVER_EXPENSE_PENDING = "GET_DRIVER_EXPENSE_PENDING";
export const GET_DRIVER_EXPENSE_SUCCESS = "GET_DRIVER_EXPENSE_SUCCESS";
export const GET_DRIVER_EXPENSE_FAILURE = "GET_DRIVER_EXPENSE_FAILURE";

export const ADD_DRIVER_EXPENSE_PENDING = "ADD_DRIVER_EXPENSE_PENDING";
export const ADD_DRIVER_EXPENSE_SUCCESS = "ADD_DRIVER_EXPENSE_SUCCESS";
export const ADD_DRIVER_EXPENSE_FAILURE = "ADD_DRIVER_EXPENSE_FAILURE";

export const UPLOAD_DRIVER_EXPENSE_PENDING = "UPLOAD_DRIVER_EXPENSE_PENDING";
export const UPLOAD_DRIVER_EXPENSE_SUCCESS = "UPLOAD_DRIVER_EXPENSE_SUCCESS";
export const UPLOAD_DRIVER_EXPENSE_FAILURE = "UPLOAD_DRIVER_EXPENSE_FAILURE";

export const EDIT_DRIVER_EXPENSE_PENDING = "EDIT_DRIVER_EXPENSE_PENDING";
export const EDIT_DRIVER_EXPENSE_SUCCESS = "EDIT_DRIVER_EXPENSE_SUCCESS";
export const EDIT_DRIVER_EXPENSE_FAILURE = "EDIT_DRIVER_EXPENSE_FAILURE";

export const DELETE_DRIVER_EXPENSE_PENDING = "DELETE_DRIVER_EXPENSE_PENDING";
export const DELETE_DRIVER_EXPENSE_SUCCESS = "DELETE_DRIVER_EXPENSE_SUCCESS";
export const DELETE_DRIVER_EXPENSE_FAILURE = "DELETE_DRIVER_EXPENSE_FAILURE";
