export const GET_TAX_PENDING = "GET_TAX_PENDING";
export const GET_TAX_SUCCESS = "GET_TAX_SUCCESS";
export const GET_TAX_FAILURE = "GET_TAX_FAILURE";

export const ADD_TAX_PENDING = "ADD_TAX_PENDING";
export const ADD_TAX_SUCCESS = "ADD_TAX_SUCCESS";
export const ADD_TAX_FAILURE = "ADD_TAX_FAILURE";

export const EDIT_TAX_PENDING = "EDIT_TAX_PENDING";
export const EDIT_TAX_SUCCESS = "EDIT_TAX_SUCCESS";
export const EDIT_TAX_FAILURE = "EDIT_TAX_FAILURE";
