export const GET_VEHICLES_REPORTS_PENDING = "GET_VEHICLES_REPORTS_PENDING"
export const GET_VEHICLES_REPORTS_SUCCESS = "GET_VEHICLES_REPORTS_SUCCESS"
export const GET_VEHICLES_REPORTS_FAILURE = "GET_VEHICLES_REPORTS_FAILURE"

export const GET_DIESELS_REPORTS_PENDING = "GET_DIESELS_REPORTS_PENDING"
export const GET_DIESELS_REPORTS_SUCCESS = "GET_DIESELS_REPORTS_SUCCESS"
export const GET_DIESELS_REPORTS_FAILURE = "GET_DIESELS_REPORTS_FAILURE"

export const GET_HARDWARE_SHOPS_REPORTS_PENDING =
  "GET_HARDWARE_SHOPS_REPORTS_PENDING"
export const GET_HARDWARE_SHOPS_REPORTS_SUCCESS =
  "GET_HARDWARE_SHOPS_REPORTS_SUCCESS"
export const GET_HARDWARE_SHOPS_REPORTS_FAILURE =
  "GET_HARDWARE_SHOPS_REPORTS_FAILURE"
