export const GET_VEHICLES_REPORTS_PENDING = "GET_VEHICLES_REPORTS_PENDING"
export const GET_VEHICLES_REPORTS_SUCCESS = "GET_VEHICLES_REPORTS_SUCCESS"
export const GET_VEHICLES_REPORTS_FAILURE = "GET_VEHICLES_REPORTS_FAILURE"